### ISSUE TITLE
[UNUSABLE PROJECT] where are the missing files?

### ISSUE THREAD

**Issue by mgesteiro** [distintiva/eBlock#1]
this project is unusable as it is: the source code lacks many of the main files (ArduinoManager, DeviceManager, ScriptsParts and UploaderEx). **Your .gitignore file is self-explanatory.**

you also removed any project configuration settings (.actionScriptProperties or .project) which would be VERY convenient for any new comer.

could you please fix this?

**Comment by distintiva** [comment]
Do you mean that there are some files that are not in the parent project (mBlock) from which this is derived ?

We have made a lot of modifications from the original project so it's possible that some files have been removed due to new impreovements.

Did you triyed to compile  from Flash Develop or any other compatible IDE ?

**Comment by mgesteiro** [comment]
Hi!

> Do you mean that there are some files that are not in the parent project (mBlock) from which this is derived ?

I explicitly indicated the files: **ArduinoManager.as**, **DeviceManager.as**, **ScriptsParts.as** and **UploaderEx.as**, which are excluded from being tracked in the repository via the **.gitignore** file.

> We have made a lot of modifications from the original project so it's possible that some files have been removed due to new impreovements.

I'm aware of that, but that is not the case here: those files **are required**
> 
> Did you triyed to compile from Flash Develop or any other compatible IDE ?

I used Adobe Flash Builder and Flash Develop: I was able to make the original project work with both of them.

To make this work you should remove the following lines from the .gitignore file and commit those changes from your local repository into github:

```
// remove this lines from the .gitignore file, recommit and push the changes to github
src/extensions/ArduinoManager.as
src/extensions/DeviceManager.as
src/extensions/UploaderEx.as
src/ui/parts/ScriptsPart.as
```
Let me remind you that this project is under GPL-2 License and code should be published (actually, you shouldn't have removed the LICENSE file from the original repository).

Best regards!

**Comment by mgesteiro** [comment]
Hi there!
Any solution to this issue?

**Comment by distintiva** [comment]
Sorry for the late reply, the person in charge of this repository can no longer manage it for a while, so we will review all the points that you comment that seem logical.

Give us a few days and we will tell you something about this issue

**Comment by distintiva** [comment]
We have already fixed  .gitignore and added the missing the related files
